#pragma once

// Client -> Server
#define HRSP_REMOTE_CLIENT_INFORMATION_PACKET  0x01
#define HRSP_REMOTE_CLIENT_STREAM_FRAME_PACKET 0x02
#define HRSP_REMOTE_CLIENT_AUDIO_DEVICE_RESULT 0x03

// Server -> Client
#define HRSP_REMOTE_SERVER_STREAM_CODE_PACKET 0x01
#define HRSP_REMOTE_SERVER_AUDIO_QUERY_DEVICE 0x02
#define HRSP_REMOTE_SERVER_AUDIO_CAPTURE      0x03
