#pragma once

#include <Windows.h>

#define HRSP_PROTOCOL_VERSION       1
#define HRSP_PROTOCOL_VERSION_MINOR 0
#define HRSP_PROTOCOL_PORT          42485
#define HRSP_PROTOCOL_PORT_STRING   "42485"

typedef struct {
	BYTE placeholder;
} HRSPPROTOCOLDATA, *PHRSPPROTOCOLDATA;

typedef enum {
	HRSP_ERROR_SUCCESS = 0,
	HRSP_ERROR_UNKNOWN_ERROR,
	HRSP_ERROR_INVALID_FUNCTION_PARAMETER,
	HRSP_ERROR_INVALID_MAGIC,
	HRSP_ERROR_UNSUPPORTED_VERSION
} HRSPPROTOCOLERRORCODE;

typedef struct {
	BOOL win32;
	LPCWSTR function;
	DWORD code;
} HRSPPROTOCOLERROR, *PHRSPPROTOCOLERROR;

#ifdef __cplusplus
extern "C" {
#endif

LPCWSTR HRSPGetErrorCode(const HRSPPROTOCOLERRORCODE code);
LPWSTR HRSPGetErrorMessage(const LPCWSTR functionName, const PHRSPPROTOCOLERROR error);

#ifdef __cplusplus
}
#endif
