#pragma once

// Client -> Server
#define HRSP_REMOTE_CLIENT_USERNAME       0x01
#define HRSP_REMOTE_CLIENT_STREAM_DEVICES 0x02

// Server -> Client
#define HRSP_REMOTE_SERVER_ACTIVATE       0x01
#define HRSP_REMOTE_SERVER_STREAM_DEVICES 0x02

typedef enum {
	HRSP_REMOTE_STREAM_DEVICE_CAMERA,
	HRSP_REMOTE_STREAM_DEVICE_PRIMARY_MONITOR,
	HRSP_REMOTE_STREAM_DEVICE_MONITOR
} HRSPREMOTESTREAMDEVICETYPE;
