/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_hackontrol_function_Screenshot */

#ifndef _Included_com_khopan_hackontrol_function_Screenshot
#define _Included_com_khopan_hackontrol_function_Screenshot
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_khopan_hackontrol_function_Screenshot
	 * Method:    take
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_khopan_hackontrol_function_Screenshot_take
	(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif
#endif
