/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_hackontrol_nativelib_power_Power */

#ifndef _Included_com_khopan_hackontrol_nativelib_power_Power
#define _Included_com_khopan_hackontrol_nativelib_power_Power
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_khopan_hackontrol_nativelib_power_Power
	 * Method:    ExitWindowsEx
	 * Signature: (IJ)I
	 */
	JNIEXPORT jint JNICALL Java_com_khopan_hackontrol_nativelib_power_Power_ExitWindowsEx
	(JNIEnv*, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
