/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_hackontrol_command_DialogCommand */

#ifndef _Included_com_khopan_hackontrol_command_DialogCommand
#define _Included_com_khopan_hackontrol_command_DialogCommand
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_khopan_hackontrol_command_DialogCommand
	 * Method:    messageBox
	 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
	 */
	JNIEXPORT void JNICALL Java_com_khopan_hackontrol_command_DialogCommand_messageBox
	(JNIEnv*, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
