/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_hackontrol_command_WakeCommand */

#ifndef _Included_com_khopan_hackontrol_command_WakeCommand
#define _Included_com_khopan_hackontrol_command_WakeCommand
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_khopan_hackontrol_command_WakeCommand
	 * Method:    wakeAddress
	 * Signature: (Lcom/khopan/hackontrol/source/CommandSource;I)V
	 */
	JNIEXPORT void JNICALL Java_com_khopan_hackontrol_command_WakeCommand_wakeAddress
	(JNIEnv*, jclass, jobject, jint);

	/*
	 * Class:     com_khopan_hackontrol_command_WakeCommand
	 * Method:    wakeAll
	 * Signature: (Lcom/khopan/hackontrol/source/CommandSource;)V
	 */
	JNIEXPORT void JNICALL Java_com_khopan_hackontrol_command_WakeCommand_wakeAll
	(JNIEnv*, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
