/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_hackontrol_command_PowerCommand */

#ifndef _Included_com_khopan_hackontrol_command_PowerCommand
#define _Included_com_khopan_hackontrol_command_PowerCommand
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_khopan_hackontrol_command_PowerCommand
	 * Method:    exitWindows
	 * Signature: (I)V
	 */
	JNIEXPORT void JNICALL Java_com_khopan_hackontrol_command_PowerCommand_exitWindows
	(JNIEnv*, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
