/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_hackontrol_installer_nativelib_TaskScheduler */

#ifndef _Included_com_khopan_hackontrol_installer_nativelib_TaskScheduler
#define _Included_com_khopan_hackontrol_installer_nativelib_TaskScheduler
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_khopan_hackontrol_installer_nativelib_TaskScheduler
	 * Method:    registerTask
	 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_khopan_hackontrol_installer_nativelib_TaskScheduler_registerTask
	(JNIEnv*, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
