/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_hackontrol_installer_nativelib_Administrator */

#ifndef _Included_com_khopan_hackontrol_installer_nativelib_Administrator
#define _Included_com_khopan_hackontrol_installer_nativelib_Administrator
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_khopan_hackontrol_installer_nativelib_Administrator
	 * Method:    hasAdministratorPrivileges
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_khopan_hackontrol_installer_nativelib_Administrator_hasAdministratorPrivileges
	(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif
#endif
