#pragma once

#include <Windows.h>

typedef struct {
	LPCWSTR address;
	LPCWSTR port;

	struct {
		BOOLEAN wsaInitialized : 1;
		BOOLEAN wsaNoCleanup : 1;
	};
} HRPSCLIENTPARAMETER, *PHRPSCLIENTPARAMETER;

typedef enum {
	HRSP_CLIENT_OK,
	HRSP_CLIENT_NULL_PARAMETER,
	HRSP_CLIENT_WSA_INITIALIZATION_FAILED,
	HRSP_CLIENT_HOST_TRANSLATION_FAILED,
	HRSP_CLIENT_CONNECTION_FAILED,
	HRSP_CLIENT_SEND_FAILED,
	HRSP_CLIENT_RECEIVE_FAILED,
	HRSP_CLIENT_SERVER_ERROR,
	HRPS_CLIENT_BCRYPT_CANNOT_OPEN_ALGORITHM,
	HRSP_CLIENT_MEMORY_ALLOCATION_FAILED,
	HRSP_CLIENT_ERROR_GENERATING_RANDOM_KEY_DATA,
	HRSP_CLIENT_ERROR_GENERATING_KEY,
	HRSP_CLIENT_WSA_CLEANUP_FAILED
} HRSPCLIENTSTATUS;

#ifdef __cplusplus
extern "C" {
#endif
HRSPCLIENTSTATUS HRSPClientConnect(const PHRPSCLIENTPARAMETER parameter);
#ifdef __cplusplus
}
#endif
